In [ ]:
import numpy as np
N=10
nums=np.array([10,20,30,40,50,60,70,80,90,100])
mean=np.mean(nums)
population_variance=np.var(nums)
simple_variance=np.var(nums,ddof=1)

print("Array : ",nums)
print("Mean : ",mean)
print("Simple Variance : ",simple_variance)
print("population_variance : ",population_variance)

Array :  [ 10  20  30  40  50  60  70  80  90 100]
Mean :  55.0
Simple Variance :  916.6666666666666
population_variance :  825.0


In [ ]:
import numpy as np
N=10
vector_x=np.array([12,65,13,21,18,24,26,11,9,10])
vector_y=np.array([22,29,32,36,42,48,12,17,21,8])

x_mean=np.mean(vector_x)
y_mean=np.mean(vector_y)

cov=np.sum((vector_x-x_mean)*(vector_y-y_mean))/(N-1)

print("vector 1 (x) : ",vector_x)
print("vector 2 (y) : ",vector_y)
print("covariance : ",cov)

vector 1 (x) :  [12 65 13 21 18 24 26 11  9 10]
vector 2 (y) :  [22 29 32 36 42 48 12 17 21  8]
covariance :  46.3


In [ ]:
import numpy as np
N=10
x=np.array([12,65,13,21,18,24,26,11,9,10])
y=np.array([22,29,32,36,42,48,12,17,21,8])

mean_x=np.mean(x)
mean_y=np.mean(y)
var_x=np.var(x,ddof=1)
var_y=np.var(y,ddof=1)
cov=np.sum((x-mean_x)*(y-mean_y))/(N-1)
correlation=cov/np.sqrt(var_x*var_y)
print("x : ",x)
print("y : ",y)
print("correlation : ",correlation)

x :  [12 65 13 21 18 24 26 11  9 10]
y :  [22 29 32 36 42 48 12 17 21  8]
correlation :  0.2140908880509667


In [ ]:
import numpy as np
M = 4
N = 5
matrix = np.array([
    [3.1,2.7,5.1,0.9],
    [1.5,3.1,6.2,1.2],
    [2.6,1.4,7.3,4.5],
    [3.5,2.3,8.4,7.8],
    [9.7,4.1,9.5,2.3]
])

cov_matrix = np.cov(matrix, ddof=0)
corr_matrix = np.corrcoef(matrix, rowvar=True)

print("Matrix:\n", matrix)
print("\nCovariance Matrix:\n", cov_matrix)
print("\nCorrelation Matrix:\n", corr_matrix)


Matrix:
 [[3.1 2.7 5.1 0.9]
 [1.5 3.1 6.2 1.2]
 [2.6 1.4 7.3 4.5]
 [3.5 2.3 8.4 7.8]
 [9.7 4.1 9.5 2.3]]

Covariance Matrix:
 [[ 2.2275  2.58    1.6275  0.505   4.035 ]
 [ 2.58    3.935   2.875   1.955   3.03  ]
 [ 1.6275  2.875   4.9625  5.46    2.385 ]
 [ 0.505   1.955   5.46    6.985   0.08  ]
 [ 4.035   3.03    2.385   0.08   10.65  ]]

Correlation Matrix:
 [[1.         0.87144199 0.48951035 0.12802634 0.82843775]
 [0.87144199 1.         0.65060174 0.37289897 0.46805346]
 [0.48951035 0.65060174 1.         0.9273831  0.32806758]
 [0.12802634 0.37289897 0.9273831  1.         0.00927539]
 [0.82843775 0.46805346 0.32806758 0.00927539 1.        ]]
